# Generated by Django 5.0.6 on 2024-07-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
    ]
